# Generated by Django 4.1.7 on 2023-04-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comasano', '0001_initial'),
    ]

    operations = [
    ]
