# Generated by Django 4.1.7 on 2023-04-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comasano', '0002_auto_20230422_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
