# Generated by Django 4.1.7 on 2023-05-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comasano', '0004_profile_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='remitente',
            new_name='destinatario',
        ),
    ]
